"""Generated by scripts/update_model_prices.py. Do not edit by hand.

These are the first-party OpenAI and Anthropic prices from the models.dev
catalog, in US dollars per 1M tokens. Each entry holds the input, output,
cache read, and cache write prices, plus the long-context tier and the
fast-mode prices where the catalog publishes them.
"""

SOURCE_URL = "https://models.dev/api.json"
FETCHED_ON = "2026-09-24"
MODELS = {
    "anthropic": {
        "claude-fable-5": {
            "cache_read": "1",
            "cache_write": "12.5",
            "input": "10",
            "output": "50"
        },
        "claude-fable-5-1": {
            "cache_read": "0.25",
            "cache_write": "12.5",
            "input": "10",
            "output": "50"
        },
        "claude-haiku-4-5": {
            "cache_read": "0.1",
            "cache_write": "1.25",
            "input": "1",
            "output": "5"
        },
        "claude-haiku-4-5-20251001": {
            "cache_read": "0.1",
            "cache_write": "1.25",
            "input": "1",
            "output": "5"
        },
        "claude-opus-4-5": {
            "cache_read": "0.5",
            "cache_write": "6.25",
            "input": "5",
            "output": "25"
        },
        "claude-opus-4-5-20251101": {
            "cache_read": "0.5",
            "cache_write": "6.25",
            "input": "5",
            "output": "25"
        },
        "claude-opus-4-6": {
            "cache_read": "0.5",
            "cache_write": "6.25",
            "input": "5",
            "output": "25"
        },
        "claude-opus-4-7": {
            "cache_read": "0.5",
            "cache_write": "6.25",
            "input": "5",
            "output": "25"
        },
        "claude-opus-4-8": {
            "cache_read": "0.5",
            "cache_write": "6.25",
            "fast": {
                "cache_read": "1",
                "cache_write": "12.5",
                "input": "10",
                "output": "50"
            },
            "input": "5",
            "output": "25"
        },
        "claude-opus-5": {
            "cache_read": "0.5",
            "cache_write": "6.25",
            "fast": {
                "cache_read": "1",
                "cache_write": "12.5",
                "input": "10",
                "output": "50"
            },
            "input": "5",
            "output": "25"
        },
        "claude-opus-5-5": {
            "cache_read": "0.2",
            "cache_write": "5",
            "fast": {
                "cache_read": "0.4",
                "cache_write": "10",
                "input": "8",
                "output": "40"
            },
            "input": "4",
            "output": "20"
        },
        "claude-sonnet-4-5": {
            "cache_read": "0.3",
            "cache_write": "3.75",
            "input": "3",
            "output": "15"
        },
        "claude-sonnet-4-5-20250929": {
            "cache_read": "0.3",
            "cache_write": "3.75",
            "input": "3",
            "output": "15"
        },
        "claude-sonnet-4-6": {
            "cache_read": "0.3",
            "cache_write": "3.75",
            "input": "3",
            "output": "15"
        },
        "claude-sonnet-5": {
            "cache_read": "0.2",
            "cache_write": "2.5",
            "input": "2",
            "output": "10"
        }
    },
    "openai": {
        "gpt-3.5-turbo": {
            "cache_read": "0",
            "input": "0.5",
            "output": "1.5"
        },
        "gpt-4": {
            "input": "30",
            "output": "60"
        },
        "gpt-4-turbo": {
            "input": "10",
            "output": "30"
        },
        "gpt-4.1": {
            "cache_read": "0.5",
            "input": "2",
            "output": "8"
        },
        "gpt-4.1-mini": {
            "cache_read": "0.1",
            "input": "0.4",
            "output": "1.6"
        },
        "gpt-4.1-nano": {
            "cache_read": "0.025",
            "input": "0.1",
            "output": "0.4"
        },
        "gpt-4o": {
            "cache_read": "1.25",
            "input": "2.5",
            "output": "10"
        },
        "gpt-4o-2024-05-13": {
            "input": "5",
            "output": "15"
        },
        "gpt-4o-2024-08-06": {
            "cache_read": "1.25",
            "input": "2.5",
            "output": "10"
        },
        "gpt-4o-2024-11-20": {
            "cache_read": "1.25",
            "input": "2.5",
            "output": "10"
        },
        "gpt-4o-mini": {
            "cache_read": "0.075",
            "input": "0.15",
            "output": "0.6"
        },
        "gpt-5": {
            "cache_read": "0.125",
            "input": "1.25",
            "output": "10"
        },
        "gpt-5-mini": {
            "cache_read": "0.025",
            "input": "0.25",
            "output": "2"
        },
        "gpt-5-nano": {
            "cache_read": "0.005",
            "input": "0.05",
            "output": "0.4"
        },
        "gpt-5-pro": {
            "input": "15",
            "output": "120"
        },
        "gpt-5.1": {
            "cache_read": "0.125",
            "input": "1.25",
            "output": "10"
        },
        "gpt-5.2": {
            "cache_read": "0.175",
            "input": "1.75",
            "output": "14"
        },
        "gpt-5.2-chat-latest": {
            "cache_read": "0.175",
            "input": "1.75",
            "output": "14"
        },
        "gpt-5.2-pro": {
            "input": "21",
            "output": "168"
        },
        "gpt-5.3-chat-latest": {
            "cache_read": "0.175",
            "input": "1.75",
            "output": "14"
        },
        "gpt-5.3-codex": {
            "cache_read": "0.175",
            "input": "1.75",
            "output": "14"
        },
        "gpt-5.3-codex-spark": {
            "cache_read": "0.175",
            "input": "1.75",
            "output": "14"
        },
        "gpt-5.4": {
            "cache_read": "0.25",
            "fast": {
                "cache_read": "0.5",
                "input": "5",
                "output": "30"
            },
            "input": "2.5",
            "long_context": {
                "cache_read": "0.5",
                "input": "5",
                "output": "22.5",
                "threshold": 272000
            },
            "output": "15"
        },
        "gpt-5.4-mini": {
            "cache_read": "0.075",
            "fast": {
                "cache_read": "0.15",
                "input": "1.5",
                "output": "9"
            },
            "input": "0.75",
            "output": "4.5"
        },
        "gpt-5.4-nano": {
            "cache_read": "0.02",
            "input": "0.2",
            "output": "1.25"
        },
        "gpt-5.4-pro": {
            "input": "30",
            "long_context": {
                "input": "60",
                "output": "270",
                "threshold": 272000
            },
            "output": "180"
        },
        "gpt-5.5": {
            "cache_read": "0.5",
            "fast": {
                "cache_read": "1.25",
                "input": "12.5",
                "output": "75"
            },
            "input": "5",
            "long_context": {
                "cache_read": "1",
                "input": "10",
                "output": "45",
                "threshold": 272000
            },
            "output": "30"
        },
        "gpt-5.5-pro": {
            "input": "30",
            "long_context": {
                "input": "60",
                "output": "270",
                "threshold": 272000
            },
            "output": "180"
        },
        "gpt-5.6": {
            "cache_read": "0.4",
            "cache_write": "5",
            "fast": {
                "cache_read": "0.8",
                "cache_write": "10",
                "input": "8",
                "output": "40"
            },
            "input": "4",
            "long_context": {
                "cache_read": "0.8",
                "cache_write": "10",
                "input": "8",
                "output": "30",
                "threshold": 272000
            },
            "output": "20"
        },
        "gpt-5.6-luna": {
            "cache_read": "0.02",
            "cache_write": "0.25",
            "fast": {
                "cache_read": "0.04",
                "cache_write": "0.5",
                "input": "0.4",
                "output": "2.4"
            },
            "input": "0.2",
            "long_context": {
                "cache_read": "0.04",
                "cache_write": "0.5",
                "input": "0.4",
                "output": "1.8",
                "threshold": 272000
            },
            "output": "1.2"
        },
        "gpt-5.6-sol": {
            "cache_read": "0.4",
            "cache_write": "5",
            "fast": {
                "cache_read": "0.8",
                "cache_write": "10",
                "input": "8",
                "output": "40"
            },
            "input": "4",
            "long_context": {
                "cache_read": "0.8",
                "cache_write": "10",
                "input": "8",
                "output": "30",
                "threshold": 272000
            },
            "output": "20"
        },
        "gpt-5.6-terra": {
            "cache_read": "0.2",
            "cache_write": "2.5",
            "fast": {
                "cache_read": "0.4",
                "cache_write": "5",
                "input": "4",
                "output": "24"
            },
            "input": "2",
            "long_context": {
                "cache_read": "0.4",
                "cache_write": "5",
                "input": "4",
                "output": "18",
                "threshold": 272000
            },
            "output": "12"
        },
        "gpt-6-astra": {
            "cache_read": "1",
            "cache_write": "12.5",
            "fast": {
                "cache_read": "2",
                "cache_write": "25",
                "input": "20",
                "output": "100"
            },
            "input": "10",
            "long_context": {
                "cache_read": "2",
                "cache_write": "25",
                "input": "20",
                "output": "75",
                "threshold": 272000
            },
            "output": "50"
        },
        "gpt-6-luna": {
            "cache_read": "0.01",
            "cache_write": "0.125",
            "fast": {
                "cache_read": "0.02",
                "cache_write": "0.25",
                "input": "0.2",
                "output": "1"
            },
            "input": "0.1",
            "long_context": {
                "cache_read": "0.02",
                "cache_write": "0.25",
                "input": "0.2",
                "output": "0.75",
                "threshold": 272000
            },
            "output": "0.5"
        },
        "gpt-6-sol": {
            "cache_read": "0.2",
            "cache_write": "2.5",
            "fast": {
                "cache_read": "0.4",
                "cache_write": "5",
                "input": "4",
                "output": "20"
            },
            "input": "2",
            "long_context": {
                "cache_read": "0.4",
                "cache_write": "5",
                "input": "4",
                "output": "15",
                "threshold": 272000
            },
            "output": "10"
        },
        "gpt-image-2": {
            "cache_read": "1.25",
            "input": "5",
            "output": "30"
        },
        "gpt-realtime-2.1": {
            "cache_read": "0.4",
            "input": "4",
            "output": "24"
        },
        "o1": {
            "cache_read": "7.5",
            "input": "15",
            "output": "60"
        },
        "o1-pro": {
            "input": "150",
            "output": "600"
        },
        "o3": {
            "cache_read": "0.5",
            "input": "2",
            "output": "8"
        },
        "o3-mini": {
            "cache_read": "0.55",
            "input": "1.1",
            "output": "4.4"
        },
        "o3-pro": {
            "input": "20",
            "output": "80"
        },
        "o4-mini": {
            "cache_read": "0.275",
            "input": "1.1",
            "output": "4.4"
        },
        "text-embedding-3-large": {
            "input": "0.13",
            "output": "0"
        },
        "text-embedding-3-small": {
            "input": "0.02",
            "output": "0"
        },
        "text-embedding-ada-002": {
            "input": "0.1",
            "output": "0"
        }
    }
}
